// @ts-check

/**
 * Generated from the docs directory, ordered by each page's sidebar_position.
 *
 * Autogenerated rather than hand-listed so adding a page is one file and not
 * two — a contributor should not have to know this file exists.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
